---
title: "Githam"
author: "Benson Zu"
date: "4/19/2021"
output: html_document
---
```{r }
library(readr) #read file
library(dplyr) #data manipulation
library(tidyr) #overall
library(lubridate) #read date
library(tibble)
library(ggplot2)
library(gridExtra)
library(ggthemes)
library(gridExtra)
```
## Years -G - water level
```{r}
#load file and clean data
githam <- read_csv("githam_water.csv")
RawData <- githam[1:3]

#separate day, month, year into different columns 
Date_date <- RawData 

Date_date$Date <- as.Date(Date_date$`Date Time, GMT+03:00`,format="%m/%d/%y") 

Final_data <- Date_date %>%
  mutate(date=format(Date, "%d"),month = format(Date, "%m"), year = format(Date, "%Y"),Date_md=format(Date,"%m/%d"))

```

```{r}
#daily average in March, April, May
Conclusion1 <- Final_data %>%
  group_by(Date_md,year) %>%
  summarise(Average_by_day_and_year = mean(as.numeric(as.character(`Water Level.`))))%>%
  ungroup()%>%
  mutate(Date_md=as.Date(Date_md, format="%m/%d"))

#Conclusion1$Date_md = as.Date(Conclusion1$Date_md , format="%m/%d")
```
```{r}
#Conclusion1$md <- paste(Conclusion1$month, Conclusion1$date,sep = "/")
#Conclusion2 <- Conclusion1
```
```{r}
p <- ggplot(data=Conclusion1,aes(x=Date_md,y=Average_by_day_and_year,color=year))+
  geom_line()+
  labs(title="Water level change in Githambara(T)",
       caption="Source:IBM") +
  scale_x_date(date_breaks= "2 weeks",date_labels="%m/%d")+
  theme(axis.text = element_text(size=8,angle=90))+
  ylab("Average Water Level(m)")+
  xlab("date")
p
```

## Years - K-water level
```{r}
#load file and clean data
#load file and clean data
K <- read_csv("karuru_water.csv")
RawData <- K[1:3]

#separate day, month, year into different columns 
Date_date <- RawData 

Date_date$Date <- as.Date(Date_date$`Date Time, GMT+03:00`,format="%Y/%m/%d") #%Y/%m/%d

Final_data <- Date_date %>%
  mutate(date=format(Date, "%d"),month = format(Date, "%m%"), year = format(Date, "%Y"),Date_md=format(Date,"%m/%d"))
```

```{r}
#daily average in March, April, May
Conclusion1 <- Final_data %>%
  group_by(Date_md,year) %>%
  summarise(Average_by_day_and_year = mean(as.numeric(as.character(`Water level (m)`))))%>%
  ungroup()%>%
  mutate(Date_md=as.Date(Date_md, format="%m/%d"))
```
```{r}
#Conclusion1$md <- paste(Conclusion1$month, Conclusion1$date,sep = "/")
#Conclusion2 <- Conclusion1
```
```{r}
p <- ggplot(data=Conclusion1,aes(x=Date_md,y=Average_by_day_and_year,color=year))+
  geom_line()+
  labs(title="Water level change in Karurumo",
       caption="Source:IBM") +
  scale_x_date(date_breaks= "2 weeks",date_labels="%m/%d")+
  theme(axis.text = element_text(size=8,angle=90))+
  ylab("Average Water Level(m)")+
  xlab("date")
p
```